### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by Mojo90** [CalebGrove/select-a-structure#4]
I just wanted to test your Plugin and unfortunately getting an error:
```
Method SelectAStructureField::__toString() must not throw an exception, caught Error: Call to a member function location() on boolean
```
This occurs even if just test with a simple minimal example and of course I followed your installation instruction. Maybe you have a fast shot? Thx!
<img width="1920" alt="screen shot 2017-04-26 at 15 23 24" src="https://cloud.githubusercontent.com/assets/2122156/25436683/5a217436-2a94-11e7-9377-d5fdab9dd847.png">
[Here](https://forum.getkirby.com/t/use-content-from-structure-in-dynamic-select-field/7328/2) you can see my fields. Could it be a problem that both are on the same page?

**Comment by calebgrove** [comment]
Well, that's strange. What version of PHP are you using? Can you copy/paste your blueprint here?

**Comment by Mojo90** [comment]
```
<?php if(!defined('KIRBY')) exit ?>
title: Standorte-Termine
pages: false
files:
  type:
    - images
fields:
  title:
    label: Title
    type:  text

  section_01:
    label: Standorte
    type: headline
  location:
    label: Standort
    type: structure
    entry: >
      {{description}}
    fields:
      key:
        label: Eindeutige Bezeichnung (Bspw. herrenberg_horberstr) --> ohne Sonderzeichen
        type: text
        required: true
      description:
        label: Standort
        type: text
        required: true
      strasse:
        label: Straße und Hausnummer
        type: text
        width: 1/2
      plz:
        label: PLZ und Ort
        type: text
        width: 1/2
      openings:
        label: Öffnungszeiten + Theorieunterricht
        type: textarea
      text:
        label: Beschreibungstext
        type: textarea


  section_02:
    label: Termine
    type: headline
  calendar:
    label: Termin-Eintrag
    type: structure
    entry: >
      <strong>{{title}}</strong><br>
      {{description}}<br>
      Start: {{_begin_date}} {{_begin_time}}<br>
      Ende: {{_end_date}} {{_end_time}}
    fields:
      title:
        label: Titel
        type: text
        required: true
      standort:
        label: Standort
        type: selectastructure
        required: true
        structurepage: standorte_termine
        structurefield: location
        optionkey: key
      description:
        label: Beschreibung
        type: textarea
        size: small
      _begin_date:
        label: Startdatum
        type: date
        format: DD.MM.YYYY
      _begin_time:
        label: Startzeit
        type: time
        interval: 15
      _end_date:
        label: Enddatum
        type: date
        format: DD.MM.YYYY
      _end_time:
        label: Endzeit
        type: time
        interval: 15
```


`PHP Version: 7.0.6`
